language: rust
cache: cargo
stages:
  - build
  - test
before_install:
  - sudo apt-get update
  - sudo apt-get install -y capnproto
  - cargo install capnpc
jobs:
  include:
    - stage: build
      script: cargo build --all-features --release --verbose
    - stage: test
      script: cargo test --verbose
