language: rust
dist: trusty
sudo: false
cache: cargo
stages:
  - build
  - test
before_install:
  - apt-get update
  - apt-get install capnproto
  - cargo install capnpc
jobs:
  include:
    - stage: build
      script: cargo build --all-features --release --verbose
    - stage: test
      script: cargo test --verbose
