language: rust
sudo: false
cache: cargo
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      script: cargo build --all-features --release --verbose
    - stage: test
      script: cargo test --verbose
